### ISSUE TITLE
Hello :)

### ISSUE THREAD

**Issue by DJANDREAJAPAN** [YoshihikoAbe/extdrm#1]
I tried using your tool, which is the extdrm to be exact, but I couldn't get this thing to work at all because of this:

(INFINITAS GAME FOLDER) /1/d/f/15d2fddc4e74a902008dc0cd6b0ce30dd32b6a6d The system cannot find the path specified.

↑ this issue above is the reason why I can't use the extdrm on the latest 2024 ver of IIDX INFINITAS ("RESOURCE: 2024080500" to be exact).

Also, I tried figuring out on how to use thing, but it was like rocket science even if I use the presets file.
If you can, could you please make this tool much more easier to decrypt the IIDX INFINITAS files please?
I have hope on this tool, because I don't know how to program a decrypting tool for the latest 2024 ver of IIDX INFINITAS.

**Comment by DJANDREAJAPAN** [comment]
And by the way, don't worry if I'm well know for decrypting the old IIDX INFINITAS (the 2015 ver tbe).
Because I want to find some lost files and some hidden easter eggs, but I'm not planing to play the cracked version online.

**Comment by YoshihikoAbe** [comment]
Could you please post the command that you are running?

**Comment by DJANDREAJAPAN** [comment]
Here you go: :)

C:\Users\andre>"E:\INFINITAS CRACKING TOOLS!!!!\extdrm.exe" dump "C:\Games\beatmania IIDX INFINITAS\game\x" "E:\INFINITAS (DUMPED FILES)" "E:\INFINITAS CRACKING TOOLS!!!!\presets\eac\infinitas_2024.json
time elapsed: 9.9606389s

This thing worked thanks to some random guy in emuline that teached me how to decrypt the 2024 ver of INFINITAS.
But before he told me that clue, I was so puzzled that I didn't know what to do.
